export const languageList = [
  { code: "", nativeName: "All" },
  { code: "ar", nativeName: "اللغة العربية" },
  { code: "de", nativeName: "Deutsch" },
  { code: "en", nativeName: "English" },
  { code: "es", nativeName: "Español" },
  { code: "fr", nativeName: "Français" },
  { code: "he", nativeName: "עברית" },
  { code: "it", nativeName: "Italiano" },
  { code: "nl", nativeName: "Nederlands" },
  { code: "no", nativeName: "Norsk" },
  { code: "pt", nativeName: "Português" },
  { code: "ru", nativeName: "Русский" },
  { code: "sv", nativeName: "Svenska" },
  { code: "zh", nativeName: "中文" },
];
